---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: webapp
    release: '0'
spec:
  containers:
  - name: nginx
    image: nginx:1.23.3-alpine
    ports:
    - containerPort: 80
---
